#CRIANDO O BANCO DE DADOS 
CREATE DATABASE loja_virtual;
USE loja_virtual;

#CRIANDO AS TABELAS DO BANCO 
CREATE TABLE PRODUTO(

id INT AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
descricao VARCHAR(250),
PRIMARY KEY (id))
Engine = innoDB;

SELECT * FROM PRODUTO;

INSERT INTO PRODUTO(nome, descricao) 
VALUES (
'NOTEBBOK',
'NOTEBBOK SAMSUNG');

INSERT INTO PRODUTO(nome, descricao) 
VALUES (
'GELADEIRA',
'GELADEIRA AZUL');
